name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
      - name: Add dependencies
        run: go mod tidy

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: go test -v ./...

  build:
    needs: [ setup, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: go build -v ./...
