name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.4'

      - name: Add depdencies
        run: go mod tidy

      - name: Test
        run: go test -v ./...

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.4'

      - name: Add depdencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...
